### ISSUE TITLE
Statistics pages sorting

### ISSUE THREAD

**Issue by kaarelkivisalu** [JarlPatrick/eoa#23]
<https://eoa.ee/?kool=true> and <https://eoa.ee/?hof=true> are not sorted properly.

<https://eoa.ee/?kool=true> is not sorted at all.

<https://eoa.ee/?hof=true> seems to be sorted by "1. KOHTI" but secont sorting parameter is random.

**Comment by marko213** [comment]
What would be good criteria for sorting these tables? First places, then second places, then third places? Total of the count of the first three places, then by the places individually?

**Comment by kaarelkivisalu** [comment]
I think overall participation might be the most relevant. For example, a student that has participated in 7 competitions but does not have any high places should be higher on the list than a person who has participated in one olympiad and achieved the third place there.

**Comment by marko213** [comment]
In that case, should all people who have participated in at least one contest be shown in the hall of fame? Currently, only students with at least one placement 1st-3rd are shown ([source](https://github.com/JarlPatrick/eoa/blob/f21fa24a75a/eoa.ee/code/hof.php#L55)).

**Comment by JarlPatrick** [comment]
I prefer sorting based on participation. But I think that we have to decide how many participations are required to get there.  Some statistics (participation-how many students):
25-1   24-1    23-2    22-1    21-4
20-3   19-1   18-3     17-6    16-3
15-5   14-11  13-10  12-13  11-23
10-16  9-24   8-26    7-55     6-95
5-110  4-238  3-362  2-599  1-1729
So I think we should include everyone who has got TOP3 or at least 8 participations (This is open for discussion).

**Comment by marko213** [comment]
Note that there are currently 450 people with at least one top 3 placement in the database (502 in total when also counting others with >= 8 participations). Should the hall of fame display be based on how many people would be shown (and the participation count be manually adjusted to match that)?
